services:
  # ANCHOR: MariaDB
  mariadb:
    build:
      context: ./mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DOCKER_PASSWORD}
      - MARIADB_DATABASE=${DOCKER_DATABASE}
      - MARIADB_USER=${DOCKER_USERNAME}
      - MARIADB_PASSWORD=${DOCKER_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"

  # ANCHOR: MongoDB
  mongo:
    build:
      context: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DOCKER_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DOCKER_PASSWORD}
      - MONGO_INITDB_DATABASE=${DOCKER_DATABASE}
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
    ports:
      - "${MONGODB_PORT}:27017"

  # ANCHOR: PostgreSQL
  postgres:
    build:
      context: ./postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
      - POSTGRES_USER=${DOCKER_USERNAME}
      - POSTGRES_DB=${DOCKER_DATABASE}
      - POSTGRES_INITDB_ARGS=--encoding=utf8 --lc-collate=C --lc-ctype=ko_KR.utf8
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  # ANCHOR: Redis
  redis:
    build:
      context: ./redis
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  mariadb:
  mongo:
  postgres:
  redis:
