services:
  # SECTION: Databases
  # ANCHOR: MariaDB
  mariadb:
    build:
      context: ./mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DOCKER_PASSWORD}
      - MARIADB_DATABASE=${DOCKER_DATABASE}
      - MARIADB_USER=${DOCKER_USERNAME}
      - MARIADB_PASSWORD=${DOCKER_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"

  # ANCHOR: MongoDB
  mongo:
    build:
      context: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DOCKER_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DOCKER_PASSWORD}
      - MONGO_INITDB_DATABASE=${DOCKER_DATABASE}
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
    ports:
      - "${MONGODB_PORT}:27017"

  # ANCHOR: PostgreSQL
  postgres:
    build:
      context: ./postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
      - POSTGRES_USER=${DOCKER_USERNAME}
      - POSTGRES_DB=${DOCKER_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  # ANCHOR: Redis
  redis:
    build:
      context: ./redis
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:6379"
  # ^SECTION

  # SECTION: Tools
  # ANCHOR: Adminer
  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER:-postgres}
    ports:
      - "${ADMINER_PORT}:8080"

  # ANCHOR: mongo-express
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${DOCKER_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DOCKER_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DOCKER_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DOCKER_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_OPTIONS_EDITORTHEME=material-palenight
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
    depends_on:
      mongo:
        condition: service_started
  # ^SECTION

volumes:
  mariadb:
  mongo:
  postgres:
  redis:
