version: "3.9"

services:
  # SECTION: Databases

  # ANCHOR: MariaDB
  mariadb:
    build:
      context: ./mariadb
      args:
        - TZ=Etc/UTC
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_DATABASE}
      - MYSQL_USER=${DOCKER_USERNAME}
      - MYSQL_PASSWORD=${DOCKER_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"

  # ANCHOR: MongoDB
  mongo:
    build:
      context: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DOCKER_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DOCKER_PASSWORD}
      - MONGO_INITDB_DATABASE=${DOCKER_DATABASE}
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
    ports:
      - "${MONGODB_PORT}:27017"

  # ANCHOR: PostgreSQL
  postgres:
    build:
      context: ./postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
      - POSTGRES_USER=${DOCKER_USERNAME}
      - POSTGRES_DB=${DOCKER_DATABASE}
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  # ANCHOR: Redis
  redis:
    build:
      context: ./redis
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:6379"

  # ^SECTION
  # SECTION: Tools

  # ANCHOR: Adminer
  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"

  # ANCHOR: mongo-express
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${DOCKER_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DOCKER_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DOCKER_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DOCKER_PASSWORD}
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
    depends_on:
      - mongo

  # ANCHOR: Mongoclient (Nosqlclient)
  mongoclient:
    image: mongoclient/mongoclient
    environment:
      - MONGOCLIENT_AUTH=true
      - MONGOCLIENT_USERNAME=${DOCKER_USERNAME}
      - MONGOCLIENT_PASSWORD=${DOCKER_PASSWORD}
    ports:
      - "${MONGOCLIENT_PORT}:3000"
    depends_on:
      - mongo

  # ANCHOR: pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DOCKER_USERNAME}@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=${DOCKER_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./postgres/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres

  # ANCHOR: Redis Commander
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - "${REDISCOMMANDER_PORT}:8081"
    depends_on:
      - redis

  # ^SECTION

volumes:
  mariadb:
  mongo:
  pgadmin:
  postgres:
  redis:
